name: Release Package

on:
  pull_request:
    types:
      - closed
    branches: 
      - main

jobs:
  release_package:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set commit author
        run: |
          git config user.name 'Candle Finance CI'
          git config user.email 'contact@trycandle.com'
      
      - name: Setup Node.js environment, including NPM
        uses: actions/setup-node@v3.0.0
        with:
          node-version: 16.13.0
          # Setting this explicitly causes an .npmrc file to be created
          # that references the NODE_AUTH_TOKEN env var defined below
          registry-url: 'https://registry.npmjs.org'

      - name: Install NPM dependencies
        run: npm install

      - name: Increment package version and commit change
        run: npm run increment-version

      - name: Push new commits to main
        uses: CasperWA/push-protected@v2.10.0
        with:
          token: ${{ secrets.ADMIN_PAT }}
          tags: true

      - name: Build TypeScript code
        run: npm run build

      - name: Publish NPM package
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
