name: Run Tests

on:
  pull_request:
    branches: 
      - main

jobs:
  run_tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      
      - name: Setup Node.js environment, including NPM
        uses: actions/setup-node@v3.0.0
        with:
          node-version: 16.13.0

      - name: Install NPM dependencies
        run: npm install

      - name: Build TypeScript code
        run: npm run build
